const financeData = {
    SE_DSA_Name: "DSA",
    customer_name_id: 40496,
    Bank_Name: "Bank",
    client: 'jmd',
    product_name_id: 12143,
    Loan_Type: "Old Car",
    Rate_of_Interest: "12",
    Loan_Number: "3543545",
    Bank_Number: "345345",
    Loan_amount: "233330",
    Loan_Disbursement_Date: "2024-02-01",
    title: "mr",
    cust_first_name: "vinay",
    cust_last_name: "kamle",
    email: "xircls@xircls.com",
    phone_no: "6867867867",
    cust_dob: "2024-01-25",
    phone_no2: "5775675675",
    address_line1: "house",
    address_line2: "stareet",
    area_building: "area",
    landmark: "hanbd",
    city: "cyt",
    state: "state",
    pincode: "yasd",
    country: "India",
    pancard: "456456",
    Adharcard: "3446534563",
    gender: "Male",
    children: "Male",
    marital_status: "inRelationship",
    occupation: "employed",
    Emi_Amount: "erert",
    no_of_tenure: "wertwert",
    frequency: "yearly",
    no_of_installment: "wertwert",
    Ex_Showroom_Amount: "wertwer",
    No_Advance_EMI: "wertwe",
    Dealer_Name: "wertw",
    Account_Type: "Saving",
    Emi_Start_Date: "2024-01-04",
    Emi_End_Date: "2024-01-21",
    Ref_title: "ms",
    Ref_first_name: "vyg",
    Ref_last_name: "yad",
    Ref_phone_no: "3453453453",
    Ref_address1: "asdfsa",
    Ref_address2: "asdfas",
    area_building_ref: "asdfa",
    landmark_ref: "sdfasdf",
    Ref_city: "asdf",
    Ref_state: "asdf",
    Ref_pincode: "asdf",
    Ref_country: 'India'
}

export default financeData